# Generated by Django 4.1.1 on 2022-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_surface_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surface',
            name='surface',
            field=models.CharField(max_length=150),
        ),
    ]
