# Generated by Django 4.1.1 on 2022-10-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_surface_surface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surface',
            old_name='surface',
            new_name='namesake',
        ),
    ]
