# Generated by Django 4.1.1 on 2022-10-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_surface_surface_namesake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='main_app.planet'),
        ),
    ]
